title: Research Blog
description: Research Blog for Deep Learning. 

url: https://dudgns0908.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
#header: large

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
#  - jekyll-archives

paginate: 10

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: dudgns0908
#  twitter:
#  facebook:
  email: dudgns09081@gmail.com
  linkedin: oldrabbit

google_analytics: "UA-58263416-1"

disqus:
    shortname: research-blog-2

#{% if page.comments %} and a {% endif %}
